### ISSUE TITLE
Pex does not build cryptography correctly

### ISSUE THREAD

**Issue by toddpalino** [linkedin/kafka-tools#10]
Looks like there's a problem with building the pex because of the use of paramiko (which requires the cryptography module). Running the pex with a command that actually executes the SSH code yields:

```python
Traceback (most recent call last):
  File "/export/home/tpalino/kafka-assigner/.bootstrap/_pex/pex.py", line 328, in execute
  File "/export/home/tpalino/kafka-assigner/.bootstrap/_pex/pex.py", line 260, in _wrap_coverage
  File "/export/home/tpalino/kafka-assigner/.bootstrap/_pex/pex.py", line 292, in _wrap_profiling
  File "/export/home/tpalino/kafka-assigner/.bootstrap/_pex/pex.py", line 371, in _execute
  File "/export/home/tpalino/kafka-assigner/.bootstrap/_pex/pex.py", line 429, in execute_entry
  File "/export/home/tpalino/kafka-assigner/.bootstrap/_pex/pex.py", line 447, in execute_pkg_resources
  File "/export/home/tpalino/.pex/install/kafka_tools-0.0.1-py2.py3-none-any.whl.7652e327fcb6d363239ac7d5348fc41002280dcd/kafka_tools-0.0.1-py2.py3-none-any.whl/kafka/tools/assigner/__main__.py", line 75, in main
    check_and_get_sizes(action_map[args.action], args, cluster, sizer_map)
  File "/export/home/tpalino/.pex/install/kafka_tools-0.0.1-py2.py3-none-any.whl.7652e327fcb6d363239ac7d5348fc41002280dcd/kafka_tools-0.0.1-py2.py3-none-any.whl/kafka/tools/assigner/__main__.py", line 32, in check_and_get_sizes
    sizer_to_run.get_partition_sizes()
  File "/export/home/tpalino/.pex/install/kafka_tools-0.0.1-py2.py3-none-any.whl.7652e327fcb6d363239ac7d5348fc41002280dcd/kafka_tools-0.0.1-py2.py3-none-any.whl/kafka/tools/assigner/sizers/ssh.py", line 32, in get_partition_sizes
    self._client.connect(broker.hostname, allow_agent=True)
  File "/export/home/tpalino/.pex/install/paramiko-2.0.1-py2.py3-none-any.whl.85adb5cee11fd6f5e7678d36e1377dd8127a20da/paramiko-2.0.1-py2.py3-none-any.whl/paramiko/client.py", line 338, in connect
    t.start_client()
  File "/export/home/tpalino/.pex/install/paramiko-2.0.1-py2.py3-none-any.whl.85adb5cee11fd6f5e7678d36e1377dd8127a20da/paramiko-2.0.1-py2.py3-none-any.whl/paramiko/transport.py", line 493, in start_client
    raise e
ImportError: /export/home/tpalino/.pex/install/cryptography-1.4-cp26-none-linux_x86_64.whl.f8504802fa31ea43dc6227a796aeb2016051ad99/cryptography-1.4-cp26-none-linux_x86_64.whl/cryptography/hazmat/bindings/_openssl.so: symbol SSL_SESSION_set1_id_context, version libssl.so.10 not defined in file libssl.so.10 with link time reference
```

**Comment by toddpalino** [comment]
Resolved by #12
