### ISSUE TITLE
remove module not working

### ISSUE THREAD

**Issue by bastianvs** [linkedin/kafka-tools#61]
[root]# kafka-assigner --tools-path /opt/kafka/bin  -z 10.146.1.234:2181 -e remove -b 3
[INFO] Connecting to zookeeper 10.146.1.234:2181
Traceback (most recent call last):
  File "/usr/bin/kafka-assigner", line 11, in <module>
    load_entry_point('kafka-tools==0.0.3', 'console_scripts', 'kafka-assigner')()
  File "/usr/lib/python3.4/site-packages/kafka_tools-0.0.3-py3.4.egg/kafka/tools/assigner/__main__.py", line 109, in main
    cluster = Cluster.create_from_zookeeper(args.zookeeper, getattr(args, 'default_retention', 1))
  File "/usr/lib/python3.4/site-packages/kafka_tools-0.0.3-py3.4.egg/kafka/tools/assigner/models/cluster.py", line 78, in create_from_zookeeper
    add_brokers_from_zk(cluster, zk)
  File "/usr/lib/python3.4/site-packages/kafka_tools-0.0.3-py3.4.egg/kafka/tools/assigner/models/cluster.py", line 32, in add_brokers_from_zk
    cluster.add_broker(Broker.create_from_json(int(b), broker_data))
  File "/usr/lib/python3.4/site-packages/kafka_tools-0.0.3-py3.4.egg/kafka/tools/assigner/models/broker.py", line 43, in create_from_json
    data = json.loads(jsondata)
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by bastianvs** [comment]
kafka-assigner  -v
0.0.3

**Comment by bastianvs** [comment]
Code is only working with python 2.7

**Comment by toddpalino** [comment]
Yeah. I have some fixed for this that are going in shortly.

**Comment by toddpalino** [comment]
This should be resolved now with #63
