### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bastianvs** [linkedin/kafka-tools#62]
Can someone please update the proper documentation for this tool. it will be more helpfull

]$ kafka-assigner -z 104:2181 --tools-path /opt/kafka/bin -e balance -t size
[INFO] Connecting to zookeeper :2181
[INFO] Getting partition list from Zookeeper
[INFO] Closing connection to zookeeper
[INFO] Getting partition sizes via SSH for 
[INFO] Getting partition sizes via SSH for 
[INFO] Getting partition sizes via SSH for 
[INFO] Starting partition balance by size
Traceback (most recent call last):
  File "/usr/bin/kafka-assigner", line 11, in <module>
    load_entry_point('kafka-tools==0.0.3', 'console_scripts', 'kafka-assigner')()
  File "/usr/lib/python2.7/site-packages/kafka_tools-0.0.3-py2.7.egg/kafka/tools/assigner/__main__.py", line 120, in main
    action_to_run.process_cluster()
  File "/usr/lib/python2.7/site-packages/kafka_tools-0.0.3-py2.7.egg/kafka/tools/assigner/actions/balance.py", line 48, in process_cluster
    bmodule.process_cluster()
  File "/usr/lib/python2.7/site-packages/kafka_tools-0.0.3-py2.7.egg/kafka/tools/assigner/actions/balancemodules/size.py", line 66, in process_cluster
    margins[pos] = (getattr(partitions[pos][sizelen // 2], self._size_attr) + getattr(partitions[pos][sizelen // 2 - 1], self._size_attr)) // 4
IndexError: list index out of range
[ ~]$ kafka-assigner --help
usage: kafka-assigner [-h] [-v] -z ZOOKEEPER [-l] [-g] [-e] [-m MOVES]
                      [-x EXCLUDE_TOPICS] [--sizer {jmx,ssh}] [-p PROPERTY]
                      [-s] [--skip-ple] [--ple-size PLE_SIZE]
                      [--ple-wait PLE_WAIT] [--tools-path TOOLS_PATH]
                      {trim,elect,set-replication-factor,clone,remove,balance,reorder}

**Comment by toddpalino** [comment]
The tool is documented fairly well in the Wiki section of this github. If there's something specific, please request that or submit a PR for the change.
